# Generated by Django 3.2.5 on 2021-07-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadedemedida', models.CharField(max_length=30, verbose_name='Unidade De Medida')),
            ],
        ),
        migrations.CreateModel(
            name='Plastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=10)),
                ('dt_criacao', models.DateField(auto_now=True)),
                ('observacao', models.CharField(max_length=256, verbose_name='Observações')),
                ('unidadedemedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadedemedida')),
            ],
        ),
        migrations.CreateModel(
            name='Papelao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=10)),
                ('dt_criacao', models.DateField(auto_now=True)),
                ('observacao', models.CharField(max_length=256, verbose_name='Observações')),
                ('unidadedemedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadedemedida')),
            ],
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=10)),
                ('dt_criacao', models.DateField(auto_now=True)),
                ('observacao', models.CharField(max_length=256, verbose_name='Observações')),
                ('unidadedemedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadedemedida')),
            ],
        ),
        migrations.CreateModel(
            name='Aluminio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=10)),
                ('dt_criacao', models.DateField(auto_now=True)),
                ('observacao', models.CharField(max_length=256, verbose_name='Observações')),
                ('unidadedemedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadedemedida')),
            ],
        ),
    ]
