# Generated by Django 3.2.5 on 2021-07-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Empresa')),
                ('email', models.EmailField(max_length=255)),
                ('cnpj', models.IntegerField(max_length=15)),
                ('telefone', models.IntegerField(max_length=15)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('cep', models.IntegerField(max_length=15)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
