# Generated by Django 3.2.5 on 2021-07-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=9)),
                ('dt_criacao', models.DateField()),
                ('observacao', models.CharField(max_length=256, verbose_name='Observações')),
            ],
        ),
        migrations.AlterField(
            model_name='aluminio',
            name='dt_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='papel',
            name='dt_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='papelao',
            name='dt_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plastico',
            name='dt_criacao',
            field=models.DateField(),
        ),
    ]
